### ISSUE TITLE
RoadMap April-Mai

### ISSUE THREAD

**Issue by Kaji0tt** [Kaji0tt/Little-Grinders#50]
- [x] Buff System Implementieren
Buff sollte eine Parent-Klasse sein, von der einzelne Buffs geerbt werden. Fähigkeiten könnte diese verwenden (e.g. MaxHeal im Combat Tree erhält einen Dornen-Effekt während die Aura aktiv ist), oder aber Projektile (Gift-Projektil applied einen Gift-Debuff auf dem Spieler)
Das ganze könnte dann so aussehen: IsometricPlayer.ApplyBuff(Dornen, duration)
oder aber nur ApplyBuff(Dornen) - hält solange, bis es entfernt wird. (RemoveBuff(Dornen))

Das Programm wird fragen (which dornen? welche instanz von dornen? - abilities oder projektile bräuchten dann eine Liste ihrer o.ä. ihrer verwendeten status effekte)

- [x] Fix den Camera-Bug wenn die Idle-Rotation verlassen wird
- [x] Fix den Bug, dass die geskillten Values der Ability erst nach Nutzung applied werden.
- [ ] Schließen von Menüs via. Escape
- [ ] Mobs mit Abilities
- [ ] Konfiguriere den Call von Sounds über EventSystem neu. //Ob das wirklich ein Unterschied macht sei dahin gestellt.

**----Spielkram-----**
- [x] Füge GFX hinzu für die Ticks vom Heil-Zauber
- [x] ggf. ein paar sounds hinzufügen für die ticks
